### ISSUE TITLE
Error, socket hang up

### ISSUE THREAD

**Issue by Conver** [mauricew/plexbot#1]
Hello,

I'm trying to get this bot to work, the bot join the network and channel just fine, but it seems it can't connect to my Plex server. This is the error I'm getting

> plexbot@0.1.0 start /home/plexbot/plexbot
> node index.js
> 
> (node:1744) UnhandledPromiseRejectionWarning: Error: socket hang up
>     at createHangUpError (_http_client.js:332:15)
>     at Socket.socketOnEnd (_http_client.js:435:23)
>     at Socket.emit (events.js:203:15)
>     at endReadableNT (_stream_readable.js:1145:12)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
> (node:1744) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error > originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1744) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Anything I can do to fix this?

**Comment by mauricew** [comment]
This is probably because I need to remove the hack I had in place to work around the plex library issue when I first made this, and also add a package-lock as well. Believe me I've got plenty to update, and I'll look more into this one day this week.

**Comment by Conver** [comment]
Thanks !! I'll see if I can get around and give you a helping hand with this, if we can get it to work smoothly, then I have a brunch of people who would like to use this.
